

service: gettokenwithauth 
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-south-1
  stage: dev
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  role: arn:aws:iam::290595126969:role/lamdaRedisaccess
  vpc:
    securityGroupIds:
      - sg-0f28b7685516f9d03
    subnetIds:
      - subnet-030c62f041193fc88
      - subnet-0187acf885fe2d73a

functions:
  Auth:
    handler: _handler.auth
    events:
      - schedule:
          name: lambda-auth-warmer
          rate: rate(5 minutes)
          enabled: true
    # events:
    #   - http:
    #       path: /
    #       method: ANY
    #       cors: true
    #       request:
    #         parameters:
    #           querystrings:
    #             token: true
    #             uid: true
  Gettoken:
    handler: _handler.gettoken
    events:
      - http:
          path: /p
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                url: true
                count: true
  UserData:
    handler: _handler.userData
    events:
      - http:
          path: /user-data
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                url: true
                count: true
      - schedule:
          name: lambda-warmer
          rate: rate(5 minutes)
          enabled: true
      # - http:
      #     path: /{proxy+}
      #     method: ANY
      #     cors: true
plugins:
  - serverless-offline

